export const queryKeys = {
  pantry: ['pantry'] as const,
  pantryItem: (id: string) => ['pantry', id] as const,
  pantryItemNutrition: (id: string, quantity: number, unit: string) => ['pantry', id, 'nutrition', quantity, unit] as const,
  recipes: ['recipes'] as const,
  recipe: (id: string) => ['recipes', id] as const,
  recipeNutritionCoverage: (id: string) => ['recipes', id, 'nutrition-coverage'] as const,
  recipeCollections: ['recipes', 'collections'] as const,
  readyToCookCount: ['recipes', 'ready-to-cook-count'] as const,
  savedRecipes: ['recipes', 'saved'] as const,
  mealPlan: ['mealPlan'] as const,
  mealPlanWeek: (weekStart: string, weekEnd: string) => ['mealPlan', weekStart, weekEnd] as const,
  cookingEvent: (id: string) => ['cookingEvent', id] as const,
  preparedMeals: ['preparedMeals'] as const,
  mealLogs: (startDate: string, endDate: string) => ['mealLogs', startDate, endDate] as const,
  groceryList: ['groceryList'] as const,
  scanHistory: ['scans', 'history'] as const,
  user: ['user'] as const,
  profileSetupStatus: ['user', 'profile-setup-status'] as const,
  kitchenImpact: (period: string, timeZone: string) => ['kitchenImpact', period, timeZone] as const,
};
